
# Optimized Netlify Configuration

[build]
  # Publication directory (default output directory for Vite)
  publish = "dist"
  # Build command with dependency resolution flag
  command = "npm install --legacy-peer-deps && npm run build"

# Cache control headers for better performance
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Cache-Control = "public, max-age=3600"

# SPA routing - redirect all paths to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
