
# Configuration Netlify optimisée

[build]
  # Répertoire de publication (répertoire de sortie de build par défaut pour Vite)
  publish = "dist"
  # Commande de build
  command = "CI= npm run build"

# Ajout d'en-têtes de cache pour améliorer les performances
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    X-Content-Type-Options = "nosniff"

# Gestion du routage SPA en redirigeant tous les chemins vers index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

